stages:
  - dependencies:
    - init
    name: generation_madgraph_pythia
    scheduler:
      parameters:
        n_events:
          output: n_events
          step: init
        proc_card:
          output: proc_card
          step: init
      scheduler_type: singlestep-stage
      workflow:
        stages:
          - dependencies: ["init"]
            name: madgraph
            scheduler:
              parameters:
                proc_card: {output: proc_card, step: init}
                n_events: {output: n_events, step: init}
                outputlhe: '{workdir}/events.lhe'
              scheduler_type: singlestep-stage
              step:
                environment:
                  environment_type: docker-encapsulated
                  image: recast/madgraph
                  imagetag: '2.6.7_v2'
                process:
                  process_type: string-interpolated-cmd
                  cmd: python steer_madgraph.py {proc_card} {outputlhe} -n {n_events}
                publisher:
                  outputmap:
                    lhefile: outputlhe
                  publisher_type: frompar-pub
          - dependencies: ["madgraph"]
            name: pythia
            scheduler:
              parameters:
                inputlhe:
                  output: lhefile
                  step: madgraph
                n_events:
                  output: n_events
                  step: init
                outputhepmc: '{workdir}/output.hepmc'
              scheduler_type: singlestep-stage
              step:
                environment:
                  environment_type: docker-encapsulated
                  image: recast/madgraph-pythia
                  imagetag: '2.6.6'
                process:
                  process_type: string-interpolated-cmd
                  cmd: 'python steer_pythia.py {inputlhe} {outputhepmc} {n_events}'
                publisher:
                  outputmap:
                    hepmc: outputhepmc
                  publisher_type: frompar-pub
  - dependencies:
    - init
    - generation_madgraph_pythia
    name: selection_rivet
    scheduler:
      parameters:
        analysis_id:
          output: analysis_id
          step: init
        hepmc:
          output: hepmc
          step: generation_madgraph_pythia
      scheduler_type: singlestep-stage
      workflow:
        stages:
        - dependencies:
          - init
          name: rivet
          scheduler:
            parameters:
              analysis:
                output: analysis
                step: init
              hepmc:
                output: input
                step: init
              output_interface:
                output: output_interface
                step: init
              output_path: '{workdir}/output'
            scheduler_type: singlestep-stage
            step:
              environment:
                environment_type: docker-encapsulated
                image: recast/rivet
                imagetag: latest
              process:
                process_type: string-interpolated-cmd
                script: 'rivet -a {analysis} -H {yoda} {hepmc}'
              publisher:
                publish:
                  yoda: '{yoda}'
                publisher_type: interpolated-pub